<?xml version="1.0" encoding="UTF-8"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1549245960190" stop="1549245966023">
	<name>Validate the title from home page</name>
	<title>Validate the title from home page</title>
	<test-cases>
		<test-case start="1549245960191" stop="1549245962923" status="passed">
			<name>Enter the correct title</name>
			<title>Enter the correct title</title>
			<description></description>
			<labels>
			</labels>
			<steps>
			</steps>
			<attachments>
				<attachment title="Screenshot" source="e1cf897d-874e-4ab5-943b-21b8b6b742a3-attachment.png" type="image/png" size="12265"/>
			</attachments>
		</test-case>
		<test-case start="1549245962924" stop="1549245966023" status="failed">
			<name>Enter the incorrect title</name>
			<title>Enter the incorrect title</title>
			<description></description>
			<labels>
			</labels>
			<steps>
			</steps>
			<attachments>
				<attachment title="Screenshot" source="3caf3825-847c-465c-af78-39f86ab851ea-attachment.png" type="image/png" size="12265"/>
			</attachments>
			<failure>
				<message>Expected &apos;Protractor practice website - Calculator&apos; to equal &apos;Protractor11 practice website - Calculator&apos;.</message>
				<stack-trace>Error: Failed expectation
    at D:\Projects\Protractor\Basics\AllureValidateTitle.js:34:27
    at ManagedPromise.invokeCallback_ (C:\Users\selenium\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\selenium\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\selenium\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\selenium\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2974:25)
    at C:\Users\selenium\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at &lt;anonymous&gt;
    at process._tickCallback (internal/process/next_tick.js:188:7)</stack-trace>
			</failure>
		</test-case>
	</test-cases>
</ns2:test-suite>