<?xml version="1.0" encoding="UTF-8"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1528295537252" stop="1528295544535">
	<name>Validate the title from home page</name>
	<title>Validate the title from home page</title>
	<test-cases>
		<test-case start="1528295537253" stop="1528295543347" status="passed">
			<name>Enter the correct title</name>
			<title>Enter the correct title</title>
			<description></description>
			<labels>
			</labels>
			<steps>
			</steps>
			<attachments>
				<attachment title="Screenshot" source="054bca96-1f05-400d-b1ae-dd392418ae83-attachment.png" type="image/png" size="12395"/>
			</attachments>
		</test-case>
		<test-case start="1528295543347" stop="1528295544534" status="failed">
			<name>Enter the incorrect title</name>
			<title>Enter the incorrect title</title>
			<description></description>
			<labels>
			</labels>
			<steps>
			</steps>
			<attachments>
				<attachment title="Screenshot" source="da4b7e23-4a96-466f-97c0-788b64cfaf6c-attachment.png" type="image/png" size="12395"/>
			</attachments>
			<failure>
				<message>Expected &apos;Protractor practice website - Calculator&apos; to equal &apos;Protractor11 practice website - Calculator&apos;.</message>
				<stack-trace>Error: Failed expectation
    at D:\Webstorm\ProtractorModules\ProtractorTest\Basics\AllureValidateTitle.js:22:27
    at ManagedPromise.invokeCallback_ (C:\Users\Poltu\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\Poltu\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\Poltu\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\Poltu\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2974:25)
    at C:\Users\Poltu\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at &lt;anonymous&gt;
    at process._tickCallback (internal/process/next_tick.js:188:7)</stack-trace>
			</failure>
		</test-case>
	</test-cases>
</ns2:test-suite>